###
get http://localhost:3000/api/todo/todos

### create todo
post http://localhost:3000/api/todo/create
Content-Type: application/json

{
    "title":"update sprint",
    "status": "ongoing"
}

### get todo by id
get http://localhost:3000/api/todo?id=2acd9f4f-573f-4556-84f0-5af3359b8456

### delete todo by id
delete http://localhost:3000/api/todo/delete?id=6101b449-192f-479f-8b35-1a5aff458017


### update todo
put http://localhost:3000/api/todo/update?id=6101b449-192f-479f-8b35-1a5aff458017
Content-Type: application/json

{
    "title": "updated todo"
}